name: "t5_trt_model"
backend: "python"
max_batch_size:0

input [
  {
    name: "input_ids"
    data_type: TYPE_INT32
    dims: [-1, -1]  # Dynamic batching and sequence length
  },
  {
    name: "attention_mask"
    data_type: TYPE_INT32
    dims: [-1, -1]  # Dynamic batch size and sequence length
  }
]

output [
  {
    name: "output_ids"
    data_type: TYPE_INT32
    dims: [-1, -1]
  }
]

instance_group [
  {
    kind: KIND_GPU
    count: 1
  }
]
